services:
  clientemqtt:
    build: ./clienteMqtt
    image: clientemqtt
    container_name: clientemqtt
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - SERVIDOR=${SERVIDOR}
      - TOPICO1=${TOPICO1}
      - TOPICO2=${TOPICO2}
      - TOPICO_PUB=${TOPICO_PUB}
    restart: unless-stopped
